[project]
name = "discogs-randomizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.14",
    "httpx>=0.28.1",
    "rich>=14.0.0",
]
